dbt_airline:
  outputs:
    dev:
      dbname: us_airline
      host: dbt_airline
      pass: abc123
      port: 5432
      schema: gold
      threads: 1
      type: postgres
      user: tester
  target: dev
