dbt_airline:
  outputs:
    dev:
      dbname: postgres
      host: "{{env_var('POSTGRES_HOST')}}"
      pass: "{{env_var('POSTGRES_PASSWORD')}}"
      port: 5432
      schema: gold
      threads: 1
      type: postgres
      user: "{{env_var('POSTGRES_USER')}}"
  target: dev


